import type { Metadata } from 'next';
import { Noto_Sans_KR as NotoSansKR } from 'next/font/google';
import '../styles/globals.scss';
import Header from '@/components/organism/Layout/Header';

const inter = NotoSansKR({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header />
        <main>{children}</main>
        <div id="modal" />
      </body>
    </html>
  );
}
